version: 0.0
os: linux
files:
  - source: cgi-bin
    destination: /var/www
  - source: index.html
    destination: /var/www/html
  - source: css
    destination: /var/www/html
  - source: img
    destination: /var/www/html
  - source: js
    destination: /var/www/html
  - source: favicon.ico
    destination: /var/www/html
permissions:
  - opject: /var/www/cgi-bin/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
