version: 0.0
os: linux
files:
  - source: cgi-bin
    destination: /var/www
  - source: index.html
    destination: /var/www/html
  - source: css
    destination: /var/www/html
  - source: img
    destination: /var/www/html
  - source: js
    destination: /var/www/html
  - source: favicon.ico
    destination: /var/www/html
permissions:
  - object: /var/www/cgi-bin/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: apache_reload.sh
      timeout: 15
      runas: root
